INSERT INTO `activity_areas` (`activityArea`) VALUES
('Aérospatial et défense'),
('Agriculture/Foresterie/Pêches'),
('Appareils et équipements médicaux'),
('Assistance personnelle et ménagère'),
('Assurances'),
('Autre/Non Classé'),
('Banques et prêts à la consommation'),
('Biotechnologie/Pharmaceutiques'),
('Commerce de détail'),
('Commerce de gros / Imporation & exportation'),
('Construction - Établissement industriel & infrastructure'),
('Construction - Résidentielle et commerciale/de bureaux'),
('Diffusion, musique et film'),
('Éducation'),
('Emploi/Agences de dotation'),
('Énergie et commodités'),
('Fabrication d\'automobiles et de pièces'),
('Fabrication de dispositifs électroniques, composants et semiconducteurs'),
('Fabrication de textiles et de vêtements'),
('Fabrication et services de la marine'),
('Fabrication, autre'),
('Gestion des déchets'),
('Hôtels et hébergement'),
('Immobilier et gestion des propriétés immobilières'),
('Imprimerie et édition'),
('Interprétation et beaux-arts'),
('Logiciel informatique'),
('Matériel informatique'),
('Métaux et minéraux'),
('Organismes caritatifs à but non-lucratif'),
('Production d\'aliments et de breuvages'),
('Produits chimiques/pétrochimiques'),
('Produits de soins personnel/Cosmétiques'),
('Restauration/Services d\'alimentation'),
('Salles de spectacles et thé&#226;tres'),
('Secteur public et gouvernemental'),
('Securité et surveillance'),
('Services aux entreprises, autre'),
('Services d\'architecture et de design'),
('Services d\'ingénierie'),
('Services de comptabilité et de vérification'),
('Services de consultation de gestion'),
('Services de location'),
('Services de publicité et de relations publiques'),
('Services de télécommunications'),
('Services des soins de santé'),
('Services financiers'),
('Services informatiques/TI'),
('Services Internet'),
('Services juridiques'),
('Sports et loisirs sportifs'),
('Transport et entreposage, matériaux'),
('Ventes d\'automobiles et services de réparation'),
('Voyage, transport et tourisme');



INSERT INTO `can_work_fors` (`description`) VALUES
('Je dois être parrainé(e) pour pouvoir travailler dans ce pays.'),
('Je suis autorisé(e) à travailler dans ce pays pour mon employeur actuel seulement.'),
('Je suis autorisé(e) à travailler dans ce pays pour n\'importe quel employeur.');



INSERT INTO `career_levels` (`careerLevel`) VALUES
('Cadre (vice-président, chef de service, etc.)'),
('Cadre supérieur (Président, trésorier)'),
('Débutant'),
('Etudiant (1er cycle/2e ou 3e cycle)'),
('Etudiant (secondaire)'),
('Expérimenté (mais pas membre de la direction)'),
('Membre de la direction (Superviseur/Chef d\'équipe)');



INSERT INTO `cover_letter_models` (`coverLetterModelName`, `TEXT`) VALUES
('Modèle 1', '2016-08-13<br /> <br /> <br /> Madame/Monsieur [nom du gestionnaire recruteur] : <br /> <br /> [si vous ne connaissez pas son nom, écrivez :]<br /> <br /> Madame/Monsieur le gestionnaire recruteur :<br /> <br /> Votre affichage de poste sur Monster concernant le poste de [titre de poste] a retenu mon attention et j\'aimerais en savoir plus sur cette possibilité d\'emploi.<br /> <br /> MONTREZ QUE VOUS AVEZ FAIT DES RECHERCHES SUR L\'ENTREPRISE : <br /> D\'après ce que j\'ai pu lire concernant votre entreprise dans [mentionnez où : article, site Web, etc.], je suis convaincu que [citez vos compétences, par exemple, expérience dans l\'électronique et la résolution de problèmes] seraient un atout au sein de votre équipe. <br /> <br /> J\'ai récemment obtenu mon [grade et domaine] à [nom de l\'établissement]. <br /> <br /> MENTIONNEZ LES FAITS SAILLANTS DE VOTRE PARCOURS UNIVERSITAIRE : <br /> Par exemple : J\'ai récemment obtenu mon grade en ingénierie, avec très grande distinction, à l\'École Polytechnique. Ou : J\'ai été lauréat du Programme national des bourses au mérite en 1998. <br /> <br /> DÉCRIVEZ LA MANIÈRE DONT VOTRE PARCOURS UNIVERSITAIRE PEUT S\'APPLIQUER AU POSTE OFFERT : <br /> Par exemple : Dans le cadre de mes études en ingénierie, j\'ai eu l\'occasion de travailler au sein d\'une équipe de développement de produit où j\'ai analysé des concepts de produit, réalisé des esquisses techniques, créé des prototypes et géré des problèmes d\'assurance de la qualité. <br /> <br /> SI VOUS AVEZ FAIT UN STAGE, AJOUTEZ : <br /> Dans le cadre de mes études en [domaine], j\'ai eu l\'occasion de faire un stage à [nom de l\'employeur], ce qui m\'a permis d\'acquérir [citez une ou plusieurs compétences]. À ce poste, j\'ai [décrivez vos principales responsabilités]. <br /> <br /> Je vous remercie de votre attention. J\'espère avoir la possibilité de discuter plus amplement de ce poste en personne, avec vous.<br /> <br /> Nous vous prions d\'accepter l\'expression de nos sentiments distingués, <br /> <br /> <br /> <br /> <br /> Alex beaulieu'),
('Modèle 2', '2016-08-13<br /> <br /> <br /> Madame/Monsieur [nom du gestionnaire recruteur] : <br /> <br /> [si vous ne connaissez pas son nom, écrivez :]<br /> <br /> Madame/Monsieur le gestionnaire recruteur :<br /> <br /> Votre affichage de poste sur Monster concernant le poste de [titre de poste] a retenu mon attention et j\'aimerais en savoir plus sur cette possibilité d\'emploi.<br /> <br /> MONTREZ QUE VOUS AVEZ FAIT DES RECHERCHES SUR L\'ENTREPRISE : <br /> D\'après ce que j\'ai pu lire concernant votre entreprise dans [mentionnez où : article, site Web, etc.], je suis convaincu que [citez vos compétences, par exemple, expérience dans l\'électronique et la résolution de problèmes] seraient un atout au sein de votre équipe. <br /> <br /> J\'ai récemment obtenu mon [grade et domaine] à [nom de l\'établissement]. <br /> <br /> MENTIONNEZ LES FAITS SAILLANTS DE VOTRE PARCOURS UNIVERSITAIRE : <br /> Par exemple : J\'ai récemment obtenu mon grade en ingénierie, avec très grande distinction, à l\'École Polytechnique. Ou : J\'ai été lauréat du Programme national des bourses au mérite en 1998. <br /> <br /> DÉCRIVEZ LA MANIÈRE DONT VOTRE PARCOURS UNIVERSITAIRE PEUT S\'APPLIQUER AU POSTE OFFERT : <br /> Par exemple : Dans le cadre de mes études en ingénierie, j\'ai eu l\'occasion de travailler au sein d\'une équipe de développement de produit où j\'ai analysé des concepts de produit, réalisé des esquisses techniques, créé des prototypes et géré des problèmes d\'assurance de la qualité. <br /> <br /> SI VOUS AVEZ FAIT UN STAGE, AJOUTEZ : <br /> Dans le cadre de mes études en [domaine], j\'ai eu l\'occasion de faire un stage à [nom de l\'employeur], ce qui m\'a permis d\'acquérir [citez une ou plusieurs compétences]. À ce poste, j\'ai [décrivez vos principales responsabilités]. <br /> <br /> Je vous remercie de votre attention. J\'espère avoir la possibilité de discuter plus amplement de ce poste en personne, avec vous.<br /> <br /> Nous vous prions d\'accepter l\'expression de nos sentiments distingués, <br /> <br /> <br /> <br /> <br /> Alex beaulieu');



INSERT INTO `cv_visibilities` (`visibilityName`, `description`) VALUES
('Visible', 'Les employeurs peuvent rechercher et consulter votre CV.'),
('Limité', 'Les employeurs peuvent rechercher et consulter votre CV, mais vos coordonnées et le nom de votre employeur actuel ne sont pas visibles.'),
('Privé', 'Les employeurs ne peuvent pas rechercher ni consulter votre CV.');



INSERT INTO `education_levels` (`educationLevel`) VALUES
('Baccalauréat'),
('Certains cours au secondaire'),
('Certification'),
('Diplôme d\'études collégiales'),
('Doctorat'),
('Formation professionnelle'),
('Maîtrise'),
('Ordre professionnel'),
('Quelques cours universitaires complétés'),
('Secondaire ou l\'équivalent');


INSERT INTO `employment_statuses` (`employmentStatus`) VALUES
('Journalier'),
('Temps partiel'),
('Temps plein');



INSERT INTO `job_types` (`jobType`) VALUES
('Employé'),
('Saisonnier'),
('Stage'),
('Temporaire / Contractuel / Projet');



INSERT INTO `languages` (`languageName`) VALUES
('Afrikaans'),
('Ainu'),
('Akkadien'),
('Albanais'),
('Allemand'),
('Alurien'),
('Amharic'),
('Anglais'),
('Anglais Hawaiien Pidgin'),
('Arabe'),
('Arkian'),
('Armenian'),
('Assamese'),
('Assyrien'),
('Asturien'),
('Autre'),
('Aymara'),
('Azerbaijani'),
('Bahasa indonésien'),
('Bas allemand'),
('Basque'),
('Basque - Euskara'),
('Belarusian'),
('Bengali'),
('Berbère'),
('birman'),
('Bosniaque'),
('Breton'),
('Buhi'),
('Bulgare'),
('Catalan'),
('Cherokee'),
('Chichewa'),
('Chinese-Shanghai Dialect'),
('Chinese-Southern Fujian Dialect'),
('Chinois'),
('Chinois - Cantonais'),
('Chinois - Mandarin'),
('Chinois – Taiwanais'),
('Cingalais'),
('Coréen'),
('Cornique'),
('Corse'),
('Croate'),
('Dakota'),
('Danois'),
('Degaspregos'),
('Dialectes aborigènes'),
('Dilhok'),
('Dongxiang'),
('Ecossais'),
('Ecossais Gaelique'),
('Egyptien'),
('Espagnol'),
('Esperanto'),
('Estonien'),
('Eurolang'),
('Féroen'),
('Fijian'),
('Finnois'),
('Français'),
('Frioulien'),
('Frisian'),
('Gaelique'),
('Gaelique irlandais'),
('Galicien'),
('Gallois'),
('Georgien'),
('Grec'),
('Grec ancien'),
('Greenlandic'),
('Guarani'),
('Gujarati'),
('Haitian Creole'),
('Haponish'),
('Hausa'),
('Hawaiien'),
('Hébreu'),
('Hindi'),
('Hindustan'),
('Hmong'),
('Hongrois'),
('Ido'),
('Ingush'),
('Irlandais'),
('Islandais'),
('Italien'),
('Jameld'),
('Japonais'),
('Kankonien'),
('Kannada'),
('Kashmiri'),
('Kazakh'),
('Khmer'),
('Kiswahili'),
('Konkani'),
('Kurde'),
('Kyrgyz'),
('Ladin'),
('Ladino'),
('Lakhota'),
('Langue des signes américaine'),
('Langue des signes anglaise'),
('Langue des signes australienne'),
('Laotian'),
('Latin'),
('Latvian'),
('Lithuanien'),
('Loglan'),
('Luxembourgeois'),
('Macédonien'),
('Malat'),
('Malay'),
('Malayalam'),
('Manipuri'),
('Manx Gaelic'),
('Maori'),
('Marathi'),
('Mongol'),
('Neelan'),
('Néerlandais'),
('Nepalais'),
('Norvégien'),
('Novial'),
('Occitan'),
('Ojibwe'),
('Oriya'),
('Pashto'),
('Perse'),
('Pidgin'),
('Pidgin Signed English (PSE) or Signed English'),
('Polonais'),
('Portugais'),
('Portugais brésilien'),
('Prakrit'),
('Punjabi'),
('Quechua'),
('Rhaeto - Romanic'),
('Romani'),
('Roumain'),
('Russe'),
('Sami'),
('Samoan'),
('Sanskrit'),
('Serbe'),
('Shiyeyi'),
('Sicilien'),
('Signing Exact English (SEE)'),
('Sindhi'),
('Slavon d\'église'),
('Slovaque'),
('Slovène'),
('Suédois'),
('Swabian'),
('Swahili'),
('Tactile Sign Language'),
('Tagalog'),
('Tamoul'),
('Tchèque'),
('Telugu'),
('Tengwar'),
('Thai'),
('Tibétain'),
('Tok Pisin'),
('Tongan'),
('Turque'),
('Ukrainien'),
('Urdu'),
('Uzbek'),
('Vietnamien'),
('Vogu'),
('Xhamagas'),
('Xhosa'),
('Yiddish'),
('Yoruba'),
('Zoulou');


INSERT INTO `language_levels` (`languageLevel`) VALUES
('Avancé'),
('Courant'),
('Débutant'),
('Intermédiaire');



INSERT INTO `phone_types` (`phoneType`) VALUES
('Autre'),
('Bureau'),
('Cellulaire'),
('Domicile');


INSERT INTO `professions` (`professionName`) VALUES
('Achat de biens et services'),
('Administration d\'hôpital/de clinique'),
('Administration de la santé publique'),
('Administration scolaire/collégiale'),
('Administration/gestion des télécommunications'),
('Analyse des conditions commerciales'),
('Analyse/recherche en valeurs mobilières'),
('Analyse/recherche/information financière'),
('Analyse/révision de crédit'),
('Architecture/décoration intérieure'),
('Arts graphiques/illustration'),
('Assurance-qualité logicielle'),
('Avis d\'imposition/recouvrement des impôts'),
('Béton et maçonnerie'),
('CAO/dessin industriel'),
('Certification ISO'),
('Charpenterie/menuiserie'),
('Commercialisation de marques'),
('Communications commerciales'),
('Comptabilité fiscale'),
('Comptabilité générale'),
('Comptabilité par fonds'),
('Comptabilité/Vérification des comptes  Analyse actuarielle'),
('Comptes créditeurs/débiteurs'),
('Conception et installation de CVCA'),
('Conception Web/IU/expérience d\'utilisateur'),
('Conception-rédaction/édition'),
('Conduite d\'automobiles, de fourgons et d\'autobus'),
('Conduite de camion'),
('Construction, mines et métiersArpentage'),
('Contrôle financier'),
('Courtage de valeurs mobilières et de marchandises'),
('Couture et confection'),
('Créativité, Design  Animatique et multimédia'),
('Crédit-bail immobilier/acquisition'),
('Design industriel'),
('Dessin de mode/d\'accessoires'),
('Développement et formation du personnel'),
('Diffusion et postproduction audio/vidéo'),
('Directeur de travaux'),
('Directeur/chef de la création'),
('Droit des brevets/de la propriété intellectuelle'),
('Droit du travail'),
('Droit fiscal'),
('Droit immobilier'),
('École primaire'),
('École secondaire'),
('Éducation spécialisée'),
('Éducation, formation, bibliothécaires'),
('Électricien'),
('Enlèvement des déchets'),
('Enquête sur les fraudes'),
('Enseignement traditionnel'),
('Estimation des coûts'),
('Évaluation foncière'),
('Examen et ajustement des réclamations'),
('Expédition et réception/entreposage'),
('Exploitation de train/de chemin de fer'),
('Fabrication de moules/moulage'),
('Fabrication et production'),
('Ferronnerie/transformation des métaux'),
('Financement des entreprises'),
('Formation continue/des adultes'),
('Formation de la clientèle'),
('Formation en logiciel/sur le Web'),
('Formation/enseignement en éducation physique et en sports'),
('Fusions et acquisitions'),
('Général/Autres : Affaires/Gestion stratégique'),
('Général/Autres : Assurance de la qualité/Sécurité'),
('Général/Autres : Comptabilité/Finance'),
('Général/Autres : Construction/Métiers spécialisés'),
('Général/Autres : Créativité/Design'),
('Général/Autres : Formation/Enseignement'),
('Général/Autres : Gestion de projet/de programme'),
('Général/Autres : Juridique'),
('Général/Autres : Logistique/Transport'),
('Général/Autres : Marketing/Produit'),
('Général/Autres : Production/Opérations'),
('Gestion de la production/d\'usine'),
('Gestion de la section commerciale'),
('Gestion de magasin/succursale'),
('Gestion de produit/Marketing'),
('Gestion de produits'),
('Gestion de programme'),
('Gestion de projet'),
('Gestion de projet en TI'),
('Gestion de projet/programme'),
('Gestion de restaurants'),
('Gestion des contrats'),
('Gestion des fournisseurs/des vendeurs'),
('Gestion des importations/exportations'),
('Gestion des investissements'),
('Gestion du risque/conformité'),
('Gestion générale'),
('Gestion hôtelière/d\'hébergement'),
('Hygiène et sécurité du travail'),
('Inspection de véhicules'),
('Installation de toitures'),
('Loi de nature réglementaire/conformité'),
('Manutention de matières dangereuses'),
('Manutention des cargaisons/des bagages'),
('Marchandisage visuel/de présentoir'),
('Marketing d\'événements/promotionnel'),
('Marketing direct (GRC)'),
('Messager'),
('Mise en pages, prépresse, impression, reliure'),
('Montage/chaâne de montage'),
('Opérateur d\'équipement'),
('Opérateur d\'équipement/de chariot élévateur/de grue'),
('Opérateur de matériel lourd'),
('Pâtudes de marché'),
('Photographie et vidéographie'),
('Pilotage : Air et mer'),
('Planchers/tuiles/peinture/papier peint'),
('Planification de la production/opérationnelle'),
('Planification et achat d\'espace médiatique'),
('Planification et achat de marchandises'),
('Planification et gestion des stocks'),
('Planification financière/conseils financiers'),
('Planification/coordination d\'événements'),
('Plaques de plâtre/plâtrage'),
('Plomberie/tuyautage'),
('Président/cadre supérieur'),
('Procureur'),
('Production et publication de documents commerciaux'),
('Production scientifique/technique'),
('Propriété d\'entreprise ou de franchise'),
('Protection de l\'environnement'),
('Qualité Six Sigma/ceinture noire/GQT'),
('Recouvrement'),
('Rédaction publicitaire (créative)'),
('Relations publiques/médiatiques ou avec les investisseurs'),
('Répartition, aiguillage et mise en route de véhicules'),
('Salon de l\'emploi'),
('Salubrité et inspection des aliments'),
('Secrétaire juridique/parajuridique'),
('Service-conseil en gestion'),
('Services de buanderie ou de nettoyage à sec'),
('Soin et développement des jeunes enfants'),
('Souscription de politiques'),
('Stratégie/planification'),
('Surveillance d\'édifices/de travaux'),
('Télémarketing'),
('Tenue des comptes/grand livre'),
('Transformation des métaux et soudure'),
('Travail à domicile'),
('Université'),
('Urbanisme'),
('Usinage/CNC'),
('Vérification');


INSERT INTO `ready_to_travels` (`description`) VALUES
('Aucun voyagement n\'est requis'),
('Jusqu\'à 100 %'),
('Jusqu\'à 25 % de voyagements'),
('Jusqu\'à 50 % de voyagements'),
('Jusqu\'à 75 % de voyagements');


INSERT INTO `roles` (`roleName`) VALUES
('Admin'),
('Candidate'),
('Enterprise');


INSERT INTO `country_regions` (`countryRegion`) VALUES
('Canada');


INSERT INTO `state_provinces` (`stateProvince`, `country_region_id`) VALUES
('Quebec', 1);


INSERT INTO `skill_cards` (`skillCard`) VALUES
('Briqueteur-Maçon'),
('Carreleur'),
('Cert. de compétence compagnon'),
('Cert. qualif. en électricité (8000 hres)'),
('Cert.qualif.mécan.d\'ascenseur(10 K hres)'),
('Charpentier-Menuisier'),
('Électricien d\'entretien'),
('Électriciens en construction'),
('Maître électricien'),
('Mécaniciens d\'escalier mobile'),
('Mécaniciens de chantier'),
('Mécaniciens de machines fixes'),
('Mécaniciens diésel'),
('Peintres en bâtiment'),
('Tuyauteurs - Plombier'),
('Tuyauteurs - poseur d\'app. de chauffage'),
('Tuyauteurs- frigoriste');


INSERT INTO `skill_levels` (`skillLevel`) VALUES
('Avancé'),
('Courant'),
('Débutant'),
('Intermédiaire');


INSERT INTO `statuses` (`statusName`) VALUES
('Actif'),
('Bannis'),
('Inactif');

INSERT INTO `working_licences` (`workingLicence`) VALUES
('Barreau du Québec'),
('Bibliothécaires'),
('Chambre des Notaires du Qc (CDNQ)'),
('Chimistes'),
('Collège des médecins du Qc (CMQ)'),
('Comptables en admin. industrielle'),
('Conseiller en orientation'),
('Ordre comptables gén. accr. du Qc (CGA)'),
('Ordre comptables man. accr. du Qc (CMA)'),
('Ordre cons. RH et rel. indust. (CRHA)'),
('Ordre des administrateurs agréés (ADMA)'),
('Ordre des architectes du Qc (OAQ)'),
('Ordre des arpenteurs-géom. du Qc (OAGQ)'),
('Ordre des comptables agréés (CA)'),
('Ordre des évaluateurs agréés du Qc (EA)'),
('Ordre des infirmières(iers) du Qc'),
('Ordre des ingénieurs du Qc (OIQ)'),
('Ordre des psychologues du Qc'),
('Ordre des travailleurs sociaux'),
('Ordre des urbanistes (OUQ)');